---
# tasks file for roles/hostname

- name: Change hostname to "hello-mahyuddin"
  hostname:
    name: "{{ inventory_hostname_short }}"
  register: "hostname_status"
  become: true
  when: ansible_hostname != inventory_hostname_short

- name: Restarting machine
  shell: sleep 2 && shutdown -r now "rebooting to complete hostname change"
  async: 1
  poll: 0
  ignore_errors: true
  become: true
  when: >
        (change_hostname_reboot is defined and
        change_hostname_reboot ) and
        hostname_status.changed

- name: Waiting for server up
  wait_for:
    host: "{{ ansible_host | default(inventory_hostname) }}"
    port: "22"
    search_regex: OpenSSH
    delay: 10
  vars:
    ansible_connection: local
  become: false
  when: >
        (change_hostname_reboot is defined and
        change_hostname_reboot ) and
        hostname_status.changed
